# Generated by Django 5.2.6 on 2025-09-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Progetto')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo Esperimento')),
                ('hypothesis', models.TextField(verbose_name='Ipotesi da testare')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('running', 'In corso'), ('completed', 'Completato')], default='draft', max_length=20)),
                ('decision', models.CharField(choices=[('pending', 'In attesa'), ('persevere', 'Persevere'), ('pivot', 'Pivot')], default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data Inizio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Fine')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Esperimento',
                'verbose_name_plural': 'Esperimenti',
                'ordering': ['-created_at'],
            },
        ),
    ]
