# Generated by Django 5.2.6 on 2025-09-30 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alias', models.CharField(max_length=100, verbose_name='Alias descrittivo')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Evento Definito',
                'verbose_name_plural': 'Eventi Definiti',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Indicatore')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('indicator_type', models.CharField(choices=[('percentage', 'Percentuale'), ('average', 'Media'), ('count', 'Conteggio'), ('revenue', 'Revenue')], default='percentage', max_length=20)),
                ('role', models.CharField(choices=[('primary', 'Primario'), ('guardrail', 'Guardrail'), ('secondary', 'Secondario')], default='primary', max_length=20)),
                ('target_uplift', models.DecimalField(decimal_places=2, help_text='Target % miglioramento (es. 10 per +10%)', max_digits=5, verbose_name='Target Uplift %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='projects.experiment')),
            ],
            options={
                'verbose_name': 'Indicatore',
                'verbose_name_plural': 'Indicatori',
                'ordering': ['experiment', '-role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateField(verbose_name='Data Misurazione')),
                ('value_control', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valore Control')),
                ('value_variant', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valore Variant')),
                ('delta_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Delta %')),
                ('decision_auto', models.CharField(blank=True, max_length=20, verbose_name='Decisione Auto')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='metrics.indicator')),
            ],
            options={
                'verbose_name': 'Risultato',
                'verbose_name_plural': 'Risultati',
                'ordering': ['-measured_at'],
            },
        ),
    ]
