# Generated by Django 5.1.1 on 2025-10-04 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='bigquery_metric_key',
            field=models.CharField(blank=True, help_text='Chiave per recuperare dati da MockBigQueryData (es: completion_rate, retention_d7)', max_length=100, verbose_name='Metric Key BigQuery'),
        ),
        migrations.CreateModel(
            name='MockBigQueryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(help_text='Identificatore metrica (es: completion_rate, retention_d7, arpu)', max_length=100)),
                ('date', models.DateField(help_text='Data a cui si riferiscono i dati aggregati')),
                ('value_control', models.DecimalField(decimal_places=4, help_text='Valore aggregato gruppo Control', max_digits=12)),
                ('value_variant', models.DecimalField(decimal_places=4, help_text='Valore aggregato gruppo Variant', max_digits=12)),
                ('sample_size_control', models.IntegerField(default=0, help_text='Numero utenti nel gruppo Control')),
                ('sample_size_variant', models.IntegerField(default=0, help_text='Numero utenti nel gruppo Variant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(help_text='Esperimento a cui si riferiscono questi dati', on_delete=django.db.models.deletion.CASCADE, related_name='mock_bigquery_data', to='projects.experiment')),
            ],
            options={
                'verbose_name': 'Mock BigQuery Data',
                'verbose_name_plural': 'Mock BigQuery Data',
                'ordering': ['-date', 'experiment', 'metric_key'],
                'unique_together': {('experiment', 'metric_key', 'date')},
            },
        ),
    ]
