# Generated by Django 5.2.6 on 2025-10-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_indicator_bigquery_metric_key_mockbigquerydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='test_type',
            field=models.CharField(choices=[('ab_test', 'A/B Test (Control vs Variant)'), ('pre_post', 'Pre/Post Test (Before vs After)'), ('single', 'Misurazione Singola (Baseline)')], default='ab_test', help_text='A/B Test per varianti parallele, Pre/Post per before/after, Single per baseline', max_length=20, verbose_name='Tipo di Test'),
        ),
    ]
