# Generated by Django 5.2.6 on 2025-10-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_indicator_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockbigquerydata',
            name='value_variant',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Valore aggregato gruppo Variant (NULL per baseline)', max_digits=12, null=True),
        ),
    ]
