# Generated by Django 5.2.6 on 2025-10-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_alter_mockbigquerydata_value_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='bigquery_query',
            field=models.TextField(blank=True, help_text='Query SQL completa per calcolare automaticamente i valori. Deve restituire le colonne: valore_control, valore_variant, uplift_percentuale (opzionale)', null=True, verbose_name='Query BigQuery SQL'),
        ),
    ]
